baseurl = "/"
title = "EDUCE - tutorials"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "EDUCE tutorials"
    description = "This blog is a collection of tutorials as part of the EDUCE data science initiative at UBC"
    github = "https://github.com/EDUCE-UBC"
    email = "psampara@mail.ubc.ca"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"