# Bash cheat sheet

+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| Command                           | Description                                                                                                                    |
+===================================+================================================================================================================================+
| `cd`                              | Change directory                                                                                                               |
|                                   |                                                                                                                                |
|                                   | `..` to parent directory                                                                                                       |
|                                   |                                                                                                                                |
|                                   | `~` to home directory                                                                                                          |
|                                   |                                                                                                                                |
|                                   | `-` to last visited directory                                                                                                  |
+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `ls`                              | List files in directory                                                                                                        |
|                                   |                                                                                                                                |
|                                   | `-l` as list                                                                                                                   |
+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `ssh <username>@<server address>` | Make a secure connection to server                                                                                             |
+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `pwd`                             | Print working directory                                                                                                        |
+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `less <filename>`                 | Look at text file                                                                                                              |
|                                   |                                                                                                                                |
|                                   | <kbd>h</kbd>elp for navigation                                                                                                 |
|                                   |                                                                                                                                |
|                                   | <kbd>q</kbd>uit                                                                                                                |
+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `scp <source> <target>`           | Copy files between local and server                                                                                            |
|                                   |                                                                                                                                |
|                                   | Give file path on server as `<user>@<server address>:<file path>`                                                              |
+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `exit`                            | Close session (either to server or to local terminal)                                                                          |
+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `history`                         | Get list of command history                                                                                                    |
|                                   |                                                                                                                                |
|                                   | Follow with `!<number>` to execute that corresponding command again                                                            |
|                                   |                                                                                                                                |
|                                   | `-a <filename>` save a history of your current session to a text file to document your work                                    |
+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `man <command>`                   | Unfortunately, it is impossible to predict how to get help for a `<command>`, try any one of these until one works             |
|                                   |                                                                                                                                |
| `help <command>`                  |                                                                                                                                |
|                                   |                                                                                                                                |
| `<command> --help`                |                                                                                                                                |
+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+
| `screen`                          | Create a virtual terminal that continues to run jobs even when your connection to the server terminates                        |
|                                   |                                                                                                                                |
|                                   | `-S <session name>` create a session with `<session name>`                                                                     |
|                                   |                                                                                                                                |
|                                   | `-ls` list all running sessions                                                                                                |
|                                   |                                                                                                                                |
|                                   | `-r <session name>` resume a session                                                                                           |
|                                   |                                                                                                                                |
|                                   | To leave a session but keep it running, first <kbd>ctrl</kbd>+<kbd>a</kbd>ctivate commands to `screen`, then <kbd>d</kbd>etach |
+-----------------------------------+--------------------------------------------------------------------------------------------------------------------------------+

: (\#tab:commands) Shell cheat sheet
